// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts from "./routes/posts.ts";
import * as $rss from "./routes/rss.ts";
import * as $PostsList from "./islands/PostsList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/posts.ts": $posts,
    "./routes/rss.ts": $rss,
  },
  islands: {
    "./islands/PostsList.tsx": $PostsList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
