// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/posts.ts";
import * as $5 from "./routes/rss.ts";
import * as $$0 from "./islands/PostsList.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/posts.ts": $4,
    "./routes/rss.ts": $5,
  },
  islands: {
    "./islands/PostsList.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
